export const projectCategories = ["Apps", "Web platforms", "AI & automation", "System software", "Games", "Devices"] as const;
export const projectStatuses = ["Live", "In development", "Prototype"] as const;
export type ProjectCategory = (typeof projectCategories)[number];
export type ProjectStatus = (typeof projectStatuses)[number];
export type ProjectShot = { src: string; alt: string; caption: string; kind?: "illustration" | "screenshot" };
export type PortfolioProject = {
  slug: string;
  title: string;
  category: ProjectCategory;
  type: string;
  description: string;
  audience: string;
  status: ProjectStatus;
  features: string[];
  stack: string[];
  platforms: string[];
  screenshots: ProjectShot[];
  website?: string | null;
  websiteLabel?: string | null;
  note?: string | null;
  featured: boolean;
  position: number;
};
